# Generated by Django 4.1.5 on 2023-05-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('img', models.ImageField(upload_to='static/faculty', verbose_name='Faculty image')),
                ('des', models.CharField(max_length=50, verbose_name='Designation')),
            ],
        ),
    ]
