# Generated by Django 4.1.5 on 2023-05-04 06:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=1000, unique=True)),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('shortdis', models.CharField(max_length=200, verbose_name='Short Discription')),
                ('content', ckeditor.fields.RichTextField()),
                ('img', models.ImageField(upload_to='static/events', verbose_name='image')),
                ('date', models.DateField(blank=True, verbose_name='Date')),
            ],
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
