# Generated by Django 4.1.5 on 2023-05-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_placements'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentachi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('file', models.FileField(upload_to='static/studentpdf', verbose_name='PDF')),
            ],
        ),
        migrations.CreateModel(
            name='teacherachi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('file', models.FileField(upload_to='static/studentpdf', verbose_name='PDF')),
            ],
        ),
    ]
