# Generated by Django 4.1.5 on 2023-05-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_studentachi_teacherachi'),
    ]

    operations = [
        migrations.CreateModel(
            name='testmonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('Profession', models.CharField(max_length=50, verbose_name='Profession')),
                ('dis', models.TextField(verbose_name='content')),
                ('img', models.ImageField(upload_to='static/testmonial', verbose_name='image')),
            ],
        ),
    ]
