# Generated by Django 4.1.5 on 2023-05-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_testmonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Mobile number')),
                ('place', models.CharField(max_length=250, verbose_name='Place')),
                ('course', models.CharField(max_length=50, verbose_name='Course')),
            ],
        ),
    ]
