# Generated by Django 4.2.1 on 2023-05-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_event_img_alter_faculty_img_alter_gallery_img_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="img",
            field=models.ImageField(
                upload_to="ipssm_web/static/events", verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="img",
            field=models.ImageField(
                upload_to="ipssm_web/static/faculty", verbose_name="Faculty image"
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="img",
            field=models.ImageField(
                upload_to="ipssm_web/static/gallery", verbose_name="Gallery"
            ),
        ),
        migrations.AlterField(
            model_name="placements",
            name="img",
            field=models.ImageField(
                upload_to="ipssm_web/static/placements", verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="studentachi",
            name="file",
            field=models.FileField(
                upload_to="ipssm_web/static/studentpdf", verbose_name="PDF"
            ),
        ),
        migrations.AlterField(
            model_name="teacherachi",
            name="file",
            field=models.FileField(
                upload_to="ipssm_web/static/studentpdf", verbose_name="PDF"
            ),
        ),
        migrations.AlterField(
            model_name="testmonials",
            name="img",
            field=models.ImageField(
                upload_to="ipssm_web/static/testmonial", verbose_name="image"
            ),
        ),
    ]
